---
- name: ansible
  become: yes
  hosts: web
  tasks: 
    - name: install nginx
      yum: 
        name: nginx
        state: latest
    - name: start nginx
      service: 
        name: nginx
        state: started
        enabled: yes
