- name: loops
  hosts: localhost 
  become: yes 
  tasks: 
    - name: print names 
      ansible.builtin.debug: 
        msg: " Hello {{item}}"
      loops:
        - Ramesh
        - Suresh
        - Robert 
        