- name: ping playbook
  hosts: localhost 
  become: no
  tasks: 
    - name: ping the server 
      ansible.builtin.ping:

    - name: print message DevOps
      ansible.builtin.debug:
        msg: "Hello DevOps"
      tags: 
        - devops

    - name: print message aws 
      ansible.builtin.debug:
        msg: "Hello AWS"
      tags: 
        - aws 